version: "3.9"
services:
  web-server:
    build:
      context: ./web-server/
    container_name: web-server
    ports:
      - "80:80"
    volumes:
      - ./app:${APP_PATCH}
      - ./web-server/config/apache2.conf:/etc/apache2/apache2.conf
      - ./web-server/config/000-default.conf:/etc/apache2/sites-available/000-default.conf